version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: capybara
    versions:
    - 3.35.1
